name: ibm-ai
channels:
  - conda-forge
  - defaults
dependencies:
  - argon2-cffi=20.1.0
  - attrs=20.1.0
  - backcall=0.2.0
  - blas=1.0
  - bleach=3.1.5
  - ca-certificates=2020.6.20
  - certifi=2020.6.20
  - cffi=1.14.2
  - colorama=0.4.3
  - convertdate=2.2.1
  - cycler=0.10.0
  - cython=0.29.21
  - decorator=4.4.2
  - defusedxml=0.6.0
  - entrypoints=0.3
  - ephem=3.7.7.1
  - fbprophet=0.6
  - freetype=2.10.2
  - holidays=0.10.3
  - icc_rt=2019.0.0
  - icu=58.2
  - importlib-metadata=1.7.0
  - importlib_metadata=1.7.0
  - intel-openmp=2020.2
  - ipykernel=5.3.4
  - ipython=7.17.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.5.1
  - jedi=0.17.2
  - jinja2=2.11.2
  - joblib=0.16.0
  - jpeg=9b
  - jsonschema=3.2.0
  - jupyter=1.0.0
  - jupyter_client=6.1.6
  - jupyter_console=6.1.0
  - jupyter_core=4.6.3
  - kiwisolver=1.2.0
  - korean_lunar_calendar=0.2.1
  - libblas=3.8.0
  - libcblas=3.8.0
  - liblapack=3.8.0
  - libpng=1.6.37
  - libpython=2.0
  - libsodium=1.0.18
  - lunarcalendar=0.0.9
  - m2w64-binutils=2.25.1
  - m2w64-bzip2=1.0.6
  - m2w64-crt-git=5.0.0.4636.2595836
  - m2w64-gcc=5.3.0
  - m2w64-gcc-ada=5.3.0
  - m2w64-gcc-fortran=5.3.0
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gcc-objc=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-headers-git=5.0.0.4636.c0ad18a
  - m2w64-isl=0.16.1
  - m2w64-libiconv=1.14
  - m2w64-libmangle-git=5.0.0.4509.2e5a9a2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - m2w64-make=4.1.2351.a80a8b8
  - m2w64-mpc=1.0.3
  - m2w64-mpfr=3.1.4
  - m2w64-pkg-config=0.29.1
  - m2w64-toolchain=5.3.0
  - m2w64-tools-git=5.0.0.4592.90b8472
  - m2w64-windows-default-manifest=6.4
  - m2w64-winpthreads-git=5.0.0.4634.697f757
  - m2w64-zlib=1.2.8
  - markupsafe=1.1.1
  - matplotlib=2.2.5
  - matplotlib-base=2.2.5
  - mistune=0.8.4
  - mkl=2020.1
  - mkl-service=2.3.0
  - msys2-conda-epoch=20160418
  - nb_conda_kernels=2.2.4
  - nbconvert=5.6.1
  - nbformat=5.0.7
  - notebook=6.1.1
  - numpy=1.19.1
  - openssl=1.1.1g
  - packaging=20.4
  - pandas=1.1.1
  - pandoc=2.10.1
  - pandocfilters=1.4.2
  - parso=0.7.0
  - pickleshare=0.7.5
  - pip=20.2.2
  - plotly=4.9.0
  - prometheus_client=0.8.0
  - prompt-toolkit=3.0.6
  - prompt_toolkit=3.0.6
  - pycparser=2.20
  - pygments=2.6.1
  - pymeeus=0.3.7
  - pyparsing=2.4.7
  - pyqt=5.9.2
  - pyrsistent=0.16.0
  - pystan=2.19.0.0
  - python=3.7.6
  - python-dateutil=2.8.1
  - python_abi=3.7
  - pytz=2020.1
  - pywin32=227
  - pywinpty=0.5.7
  - pyzmq=19.0.1
  - qt=5.9.7
  - qtconsole=4.7.6
  - qtpy=1.9.0
  - retrying=1.3.3
  - scikit-learn=0.23.2
  - scipy=1.5.2
  - send2trash=1.5.0
  - setuptools=49.6.0
  - sip=4.19.8
  - six=1.15.0
  - sqlite=3.33.0
  - terminado=0.8.3
  - testpath=0.4.4
  - threadpoolctl=2.1.0
  - tornado=6.0.4
  - traitlets=4.3.3
  - vc=14.1
  - vs2015_runtime=14.16.27012
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.35.1
  - widgetsnbextension=3.5.1
  - wincertstore=0.2
  - winpty=0.4.3
  - zeromq=4.3.2
  - zipp=3.1.0
  - zlib=1.2.11

